export const courses = [
  {
    id: 1,
    name: 'Full-Stack Web Development',
    category: 'Programming',
    duration: 12,
    level: 'Intermediate',
    description: 'Master modern web development with React, Node.js, and databases. Build real-world applications from scratch and deploy them to production.',
    skills: ['React', 'Node.js', 'MongoDB', 'Express', 'JavaScript'],
    price: 299,
    mentorCount: 15,
    studentCount: 450,
    rating: 4.8,
    image: 'src/assets/4380747.jpg',
  },
  {
    id: 2,
    name: 'UI/UX Design Mastery',
    category: 'Design',
    duration: 10,
    level: 'Beginner',
    description: 'Learn user-centered design principles, create stunning interfaces, and build a portfolio that gets you hired. Includes Figma, prototyping, and user research.',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Wireframing'],
    price: 249,
    mentorCount: 12,
    studentCount: 380,
    rating: 4.9,
    image: 'src/assets/5775839.jpg',
  },
  {
    id: 3,
    name: 'Data Science & Analytics',
    category: 'Data',
    duration: 14,
    level: 'Advanced',
    description: 'Transform data into insights using Python, SQL, and machine learning. Work with real datasets and build predictive models for business decisions.',
    skills: ['Python', 'SQL', 'Machine Learning', 'Pandas', 'Data Visualization'],
    price: 349,
    mentorCount: 18,
    studentCount: 520,
    rating: 4.7,
    image: 'src/assets/business-data-analysis.jpg',
  },
  {
    id: 4,
    name: 'Digital Marketing Strategy',
    category: 'Marketing',
    duration: 8,
    level: 'Beginner',
    description: 'Master social media marketing, SEO, content strategy, and analytics. Learn to grow brands and drive conversions with data-driven campaigns.',
    skills: ['SEO', 'Social Media', 'Content Marketing', 'Analytics', 'PPC'],
    price: 199,
    mentorCount: 10,
    studentCount: 320,
    rating: 4.6,
    image: 'src/assets/9812.jpg',
  },
  {
    id: 5,
    name: 'Cloud Architecture & DevOps',
    category: 'Cloud',
    duration: 12,
    level: 'Intermediate',
    description: 'Deploy scalable applications on AWS, Azure, and GCP. Master Docker, Kubernetes, CI/CD pipelines, and infrastructure as code.',
    skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Terraform'],
    price: 399,
    mentorCount: 14,
    studentCount: 280,
    rating: 4.9,
    image: 'src/assets/877.jpg',
  },
  {
    id: 6,
    name: 'Product Management Fundamentals',
    category: 'Business',
    duration: 10,
    level: 'Intermediate',
    description: 'Learn to build products users love. Master product strategy, roadmapping, user stories, and work with cross-functional teams.',
    skills: ['Product Strategy', 'Roadmapping', 'User Stories', 'Agile', 'Analytics'],
    price: 279,
    mentorCount: 11,
    studentCount: 410,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 7,
    name: 'Mobile App Development',
    category: 'Programming',
    duration: 14,
    level: 'Intermediate',
    description: 'Build native and cross-platform mobile apps with React Native and Flutter. Learn app design, state management, and publishing to app stores.',
    skills: ['React Native', 'Flutter', 'iOS', 'Android', 'State Management'],
    price: 329,
    mentorCount: 13,
    studentCount: 360,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 8,
    name: 'AI & Machine Learning',
    category: 'AI',
    duration: 16,
    level: 'Advanced',
    description: 'Deep dive into artificial intelligence and machine learning. Build neural networks, work with NLP, computer vision, and deploy ML models.',
    skills: ['TensorFlow', 'PyTorch', 'Neural Networks', 'NLP', 'Computer Vision'],
    price: 449,
    mentorCount: 16,
    studentCount: 290,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 9,
    name: 'Content Writing & Copywriting',
    category: 'Writing',
    duration: 6,
    level: 'Beginner',
    description: 'Master the art of persuasive writing. Learn to create engaging content, write compelling copy, and build a writing portfolio.',
    skills: ['Copywriting', 'SEO Writing', 'Content Strategy', 'Editing', 'Storytelling'],
    price: 149,
    mentorCount: 8,
    studentCount: 250,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 10,
    name: 'Cybersecurity Essentials',
    category: 'Security',
    duration: 12,
    level: 'Intermediate',
    description: 'Protect systems and data from threats. Learn ethical hacking, network security, cryptography, and security best practices.',
    skills: ['Ethical Hacking', 'Network Security', 'Cryptography', 'Penetration Testing', 'Security Auditing'],
    price: 379,
    mentorCount: 12,
    studentCount: 220,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 11,
    name: 'Project Management Professional',
    category: 'Business',
    duration: 10,
    level: 'Intermediate',
    description: 'Master project management methodologies, tools, and techniques. Learn to lead teams, manage budgets, and deliver projects successfully.',
    skills: ['Agile', 'Scrum', 'Project Planning', 'Risk Management', 'Stakeholder Management'],
    price: 269,
    mentorCount: 9,
    studentCount: 340,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 12,
    name: 'Sales & Business Development',
    category: 'Business',
    duration: 8,
    level: 'Beginner',
    description: 'Learn sales techniques, negotiation skills, and business development strategies. Build relationships and close deals effectively.',
    skills: ['Sales Techniques', 'Negotiation', 'CRM', 'Lead Generation', 'Client Relations'],
    price: 199,
    mentorCount: 7,
    studentCount: 280,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80',
  },
]

// Helper function to get courses by category
export const getCoursesByCategory = (category) => {
  return courses.filter((course) => course.category === category)
}

// Helper function to get course by ID
export const getCourseById = (id) => {
  return courses.find((course) => course.id === id)
}

// Helper function to search courses
export const searchCourses = (query) => {
  const lowerQuery = query.toLowerCase()
  return courses.filter(
    (course) =>
      course.name.toLowerCase().includes(lowerQuery) ||
      course.description.toLowerCase().includes(lowerQuery) ||
      course.category.toLowerCase().includes(lowerQuery) ||
      course.skills.some((skill) => skill.toLowerCase().includes(lowerQuery)),
  )
}

// Get all unique categories
export const getCategories = () => {
  return [...new Set(courses.map((course) => course.category))]
}

// Comprehensive Mentors Data - 50 Mentors from Different Career Fields
export const mentors = [
  {
    id: 1,
    name: 'Aisha Khan',
    role: 'Product Designer',
    company: 'Google',
    focus: 'Portfolio-ready UX projects and case studies',
    rating: 4.9,
    assured: true,
    experience: 6,
    hourlyRate: 75,
    bio: 'Senior Product Designer with 6+ years of experience creating user-centered designs for leading tech companies. Specialized in design systems, user research, and building products that users love.',
    skills: ['UI/UX Design', 'Figma', 'User Research', 'Prototyping', 'Design Systems'],
    education: [
      { degree: 'BFA in Graphic Design', institution: 'Rhode Island School of Design', year: 2018 },
    ],
    certifications: ['Google UX Design Certificate', 'Figma Advanced Certification'],
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=320&q=80',
    courses: [2, 6],
  },
  {
    id: 2,
    name: 'Ryan Patel',
    role: 'Software Engineer',
    company: 'Microsoft',
    focus: 'Full-stack skills, system design, interview prep',
    rating: 4.8,
    assured: false,
    experience: 5,
    hourlyRate: 85,
    bio: 'Full-stack engineer with expertise in building scalable web applications. Passionate about mentoring and helping developers land their dream jobs at top tech companies.',
    skills: ['React', 'Node.js', 'TypeScript', 'System Design', 'AWS'],
    education: [
      { degree: 'BS in Computer Science', institution: 'Stanford University', year: 2019 },
    ],
    certifications: ['AWS Certified Solutions Architect', 'React Advanced Patterns'],
    image: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=320&q=80',
    courses: [1, 5, 7],
  },
  {
    id: 3,
    name: 'Mei Chen',
    role: 'Data Scientist',
    company: 'Amazon',
    focus: 'Analytics projects, SQL, storytelling with data',
    rating: 5.0,
    assured: true,
    experience: 7,
    hourlyRate: 95,
    bio: 'Data scientist with 7 years of experience in machine learning and analytics. Expert in Python, SQL, and building data-driven products that drive business decisions.',
    skills: ['Python', 'SQL', 'Machine Learning', 'Data Visualization', 'Statistics'],
    education: [
      { degree: 'MS in Data Science', institution: 'MIT', year: 2017 },
      { degree: 'BS in Mathematics', institution: 'UC Berkeley', year: 2015 },
    ],
    certifications: ['TensorFlow Developer Certificate', 'Google Data Analytics Certificate'],
    image: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=320&q=80',
    courses: [3, 8],
  },
  {
    id: 4,
    name: 'Carlos Diaz',
    role: 'Marketing Lead',
    company: 'Meta',
    focus: 'Growth strategy, content that converts, GTM basics',
    rating: 4.7,
    assured: false,
    experience: 8,
    hourlyRate: 70,
    bio: 'Marketing strategist with 8 years of experience in growth marketing and content strategy. Helped scale multiple startups from 0 to millions in revenue.',
    skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Growth Hacking', 'Analytics'],
    education: [
      { degree: 'MBA in Marketing', institution: 'Harvard Business School', year: 2016 },
    ],
    certifications: ['Google Analytics Certified', 'HubSpot Content Marketing'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=320&q=80',
    courses: [4, 12],
  },
  {
    id: 5,
    name: 'Sarah Johnson',
    role: 'Cloud Architect',
    company: 'Apple',
    focus: 'AWS, DevOps, scalable infrastructure',
    rating: 4.9,
    assured: true,
    experience: 9,
    hourlyRate: 100,
    bio: 'Cloud architect with expertise in designing and deploying scalable infrastructure on AWS. Certified AWS Solutions Architect with experience across multiple industries.',
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    education: [
      { degree: 'BS in Computer Engineering', institution: 'Georgia Tech', year: 2015 },
    ],
    certifications: ['AWS Solutions Architect Professional', 'Kubernetes Administrator'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [5, 10],
  },
  {
    id: 6,
    name: 'David Kim',
    role: 'Mobile Developer',
    company: 'Meta',
    focus: 'React Native, iOS, Android development',
    rating: 4.8,
    assured: true,
    experience: 6,
    hourlyRate: 80,
    bio: 'Mobile developer specializing in cross-platform app development. Built apps with millions of downloads and expertise in React Native and native iOS/Android.',
    skills: ['React Native', 'iOS', 'Android', 'Swift', 'Kotlin'],
    education: [
      { degree: 'BS in Software Engineering', institution: 'Carnegie Mellon', year: 2018 },
    ],
    certifications: ['Apple Developer Certification', 'React Native Advanced'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [7],
  },
  {
    id: 7,
    name: 'Priya Sharma',
    role: 'Product Manager',
    company: 'Microsoft',
    focus: 'Product strategy, roadmapping, agile methodologies',
    rating: 4.9,
    assured: true,
    experience: 7,
    hourlyRate: 90,
    bio: 'Product manager with 7 years of experience building B2B and B2C products. Expert in product strategy, user research, and working with engineering teams.',
    skills: ['Product Strategy', 'Roadmapping', 'Agile', 'User Research', 'Analytics'],
    education: [
      { degree: 'MBA', institution: 'Wharton School', year: 2017 },
      { degree: 'BS in Engineering', institution: 'IIT Delhi', year: 2015 },
    ],
    certifications: ['Certified Scrum Product Owner', 'Google Analytics'],
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=320&q=80',
    courses: [6, 11],
  },
  {
    id: 8,
    name: 'James Wilson',
    role: 'Cybersecurity Expert',
    company: 'CrowdStrike',
    focus: 'Ethical hacking, network security, penetration testing',
    rating: 4.8,
    assured: true,
    experience: 10,
    hourlyRate: 110,
    bio: 'Cybersecurity expert with 10 years of experience in ethical hacking and security auditing. Certified ethical hacker helping organizations secure their infrastructure.',
    skills: ['Ethical Hacking', 'Network Security', 'Penetration Testing', 'Cryptography', 'Security Auditing'],
    education: [
      { degree: 'MS in Cybersecurity', institution: 'Johns Hopkins', year: 2014 },
    ],
    certifications: ['CEH', 'CISSP', 'Security+'],
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=320&q=80',
    courses: [10],
  },
  {
    id: 9,
    name: 'Emma Thompson',
    role: 'Content Strategist',
    company: 'Contentful',
    focus: 'Content writing, SEO, brand storytelling',
    rating: 4.6,
    assured: false,
    experience: 5,
    hourlyRate: 65,
    bio: 'Content strategist and writer with expertise in SEO, brand storytelling, and content marketing. Helped multiple brands grow their audience through strategic content.',
    skills: ['Content Writing', 'SEO', 'Copywriting', 'Content Strategy', 'Editing'],
    education: [
      { degree: 'BA in English Literature', institution: 'Oxford University', year: 2019 },
    ],
    certifications: ['Content Marketing Institute Certification'],
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=320&q=80',
    courses: [9],
  },
  {
    id: 10,
    name: 'Michael Chen',
    role: 'AI/ML Engineer',
    company: 'OpenAI',
    focus: 'Machine learning, neural networks, NLP',
    rating: 5.0,
    assured: true,
    experience: 8,
    hourlyRate: 120,
    bio: 'AI/ML engineer with expertise in deep learning, NLP, and computer vision. Published researcher and contributor to open-source ML projects.',
    skills: ['TensorFlow', 'PyTorch', 'Neural Networks', 'NLP', 'Computer Vision'],
    education: [
      { degree: 'PhD in Machine Learning', institution: 'Stanford University', year: 2016 },
      { degree: 'MS in Computer Science', institution: 'Stanford University', year: 2013 },
    ],
    certifications: ['TensorFlow Developer Certificate', 'Deep Learning Specialization'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=320&q=80',
    courses: [8],
  },
  {
    id: 11,
    name: 'Lisa Anderson',
    role: 'Project Manager',
    company: 'Accenture',
    focus: 'Agile, Scrum, project delivery',
    rating: 4.7,
    assured: true,
    experience: 9,
    hourlyRate: 75,
    bio: 'Certified project manager with 9 years of experience leading cross-functional teams. Expert in Agile, Scrum, and delivering complex projects on time and budget.',
    skills: ['Agile', 'Scrum', 'Project Planning', 'Risk Management', 'Stakeholder Management'],
    education: [
      { degree: 'PMP Certification', institution: 'PMI', year: 2015 },
      { degree: 'BS in Business Administration', institution: 'NYU', year: 2012 },
    ],
    certifications: ['PMP', 'Certified Scrum Master', 'Agile Certified Practitioner'],
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=320&q=80',
    courses: [11],
  },
  {
    id: 12,
    name: 'Robert Martinez',
    role: 'Sales Director',
    company: 'Salesforce',
    focus: 'Sales strategy, negotiation, business development',
    rating: 4.8,
    assured: true,
    experience: 12,
    hourlyRate: 85,
    bio: 'Sales leader with 12 years of experience in B2B sales and business development. Expert in building sales teams and closing enterprise deals.',
    skills: ['Sales Strategy', 'Negotiation', 'CRM', 'Lead Generation', 'Client Relations'],
    education: [
      { degree: 'BS in Business', institution: 'University of Texas', year: 2012 },
    ],
    certifications: ['Salesforce Certified Administrator', 'Salesforce Sales Cloud'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=320&q=80',
    courses: [12],
  },
  {
    id: 13,
    name: 'Jennifer Lee',
    role: 'Frontend Engineer',
    company: 'Netflix',
    focus: 'React, Vue.js, modern JavaScript frameworks',
    rating: 4.9,
    assured: true,
    experience: 6,
    hourlyRate: 88,
    bio: 'Frontend engineer specializing in building responsive and performant user interfaces. Expert in React ecosystem and modern JavaScript development.',
    skills: ['React', 'Vue.js', 'JavaScript', 'TypeScript', 'CSS'],
    education: [
      { degree: 'BS in Computer Science', institution: 'UC San Diego', year: 2018 },
    ],
    certifications: ['React Developer Certification'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [1],
  },
  {
    id: 14,
    name: 'Alex Rodriguez',
    role: 'Backend Engineer',
    company: 'Uber',
    focus: 'Microservices, API design, database optimization',
    rating: 4.8,
    assured: true,
    experience: 7,
    hourlyRate: 92,
    bio: 'Backend engineer with expertise in building scalable microservices and APIs. Specialized in system architecture and database design for high-traffic applications.',
    skills: ['Java', 'Python', 'Microservices', 'API Design', 'PostgreSQL'],
    education: [
      { degree: 'MS in Computer Science', institution: 'UC Berkeley', year: 2017 },
    ],
    certifications: ['AWS Certified Developer'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [1, 5],
  },
  {
    id: 15,
    name: 'Sophie Brown',
    role: 'UX Researcher',
    company: 'Google',
    focus: 'User research, usability testing, design thinking',
    rating: 4.9,
    assured: true,
    experience: 5,
    hourlyRate: 78,
    bio: 'UX researcher with expertise in qualitative and quantitative research methods. Helps teams build products based on real user insights and data.',
    skills: ['User Research', 'Usability Testing', 'Design Thinking', 'Analytics', 'Prototyping'],
    education: [
      { degree: 'MS in Human-Computer Interaction', institution: 'Carnegie Mellon', year: 2019 },
    ],
    certifications: ['Google UX Research Certificate'],
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=320&q=80',
    courses: [2],
  },
  {
    id: 16,
    name: 'Kevin Zhang',
    role: 'DevOps Engineer',
    company: 'GitHub',
    focus: 'CI/CD pipelines, infrastructure automation, monitoring',
    rating: 4.8,
    assured: true,
    experience: 8,
    hourlyRate: 95,
    bio: 'DevOps engineer specializing in CI/CD, infrastructure as code, and cloud automation. Expert in building reliable deployment pipelines.',
    skills: ['Docker', 'Kubernetes', 'Jenkins', 'Terraform', 'Monitoring'],
    education: [
      { degree: 'BS in Computer Science', institution: 'University of Washington', year: 2016 },
    ],
    certifications: ['Kubernetes Administrator', 'Terraform Associate'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=320&q=80',
    courses: [5],
  },
  {
    id: 17,
    name: 'Maria Garcia',
    role: 'Data Analyst',
    company: 'Airbnb',
    focus: 'SQL, data visualization, business intelligence',
    rating: 4.7,
    assured: false,
    experience: 4,
    hourlyRate: 68,
    bio: 'Data analyst with expertise in SQL, data visualization, and business intelligence. Helps companies make data-driven decisions through insightful analysis.',
    skills: ['SQL', 'Python', 'Tableau', 'Excel', 'Statistics'],
    education: [
      { degree: 'BS in Statistics', institution: 'UCLA', year: 2020 },
    ],
    certifications: ['Google Data Analytics Certificate'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [3],
  },
  {
    id: 18,
    name: 'Thomas Anderson',
    role: 'Full-Stack Developer',
    company: 'Shopify',
    focus: 'MERN stack, e-commerce platforms, API integration',
    rating: 4.9,
    assured: true,
    experience: 6,
    hourlyRate: 85,
    bio: 'Full-stack developer with expertise in building e-commerce platforms and web applications. Specialized in MERN stack and payment integrations.',
    skills: ['MongoDB', 'Express', 'React', 'Node.js', 'Payment APIs'],
    education: [
      { degree: 'BS in Software Engineering', institution: 'University of Waterloo', year: 2018 },
    ],
    certifications: ['MongoDB Certified Developer'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [1],
  },
  {
    id: 19,
    name: 'Rachel Kim',
    role: 'Graphic Designer',
    company: 'Adobe',
    focus: 'Brand identity, visual design, creative direction',
    rating: 4.8,
    assured: true,
    experience: 7,
    hourlyRate: 72,
    bio: 'Graphic designer with expertise in brand identity and visual design. Creates compelling visual experiences for brands across digital and print media.',
    skills: ['Adobe Creative Suite', 'Brand Identity', 'Typography', 'Illustration', 'Print Design'],
    education: [
      { degree: 'BFA in Graphic Design', institution: 'Art Center College of Design', year: 2017 },
    ],
    certifications: ['Adobe Certified Expert'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [2],
  },
  {
    id: 20,
    name: 'Daniel Park',
    role: 'QA Engineer',
    company: 'Microsoft',
    focus: 'Test automation, quality assurance, bug tracking',
    rating: 4.6,
    assured: false,
    experience: 5,
    hourlyRate: 70,
    bio: 'QA engineer specializing in test automation and quality assurance. Expert in building comprehensive test suites and ensuring software quality.',
    skills: ['Selenium', 'Jest', 'Cypress', 'Test Automation', 'Bug Tracking'],
    education: [
      { degree: 'BS in Computer Science', institution: 'University of Illinois', year: 2019 },
    ],
    certifications: ['ISTQB Certified Tester'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [1],
  },
  {
    id: 21,
    name: 'Olivia White',
    role: 'Social Media Manager',
    company: 'TikTok',
    focus: 'Social media strategy, content creation, community management',
    rating: 4.7,
    assured: false,
    experience: 4,
    hourlyRate: 60,
    bio: 'Social media manager with expertise in building brand presence across platforms. Creates engaging content and manages online communities.',
    skills: ['Social Media', 'Content Creation', 'Community Management', 'Analytics', 'Influencer Marketing'],
    education: [
      { degree: 'BA in Communications', institution: 'USC', year: 2020 },
    ],
    certifications: ['Hootsuite Social Media Marketing'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [4],
  },
  {
    id: 22,
    name: 'Nathan Taylor',
    role: 'Blockchain Developer',
    company: 'Coinbase',
    focus: 'Smart contracts, DeFi, Web3 development',
    rating: 4.9,
    assured: true,
    experience: 5,
    hourlyRate: 105,
    bio: 'Blockchain developer with expertise in smart contracts and DeFi protocols. Builds decentralized applications on Ethereum and other blockchains.',
    skills: ['Solidity', 'Ethereum', 'Web3', 'Smart Contracts', 'DeFi'],
    education: [
      { degree: 'BS in Computer Science', institution: 'MIT', year: 2019 },
    ],
    certifications: ['Ethereum Developer Certification'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [1],
  },
  {
    id: 23,
    name: 'Isabella Martinez',
    role: 'SEO Specialist',
    company: 'Moz',
    focus: 'Search engine optimization, keyword research, technical SEO',
    rating: 4.8,
    assured: true,
    experience: 6,
    hourlyRate: 65,
    bio: 'SEO specialist with expertise in improving search rankings and organic traffic. Expert in technical SEO, keyword research, and content optimization.',
    skills: ['SEO', 'Keyword Research', 'Technical SEO', 'Analytics', 'Link Building'],
    education: [
      { degree: 'BS in Marketing', institution: 'University of Florida', year: 2018 },
    ],
    certifications: ['Google SEO Certification', 'Moz SEO Certification'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [4],
  },
  {
    id: 24,
    name: 'Christopher Lee',
    role: 'Game Developer',
    company: 'Epic Games',
    focus: 'Unity, game design, 3D modeling',
    rating: 4.7,
    assured: false,
    experience: 5,
    hourlyRate: 82,
    bio: 'Game developer specializing in Unity and Unreal Engine. Creates engaging gameplay experiences and interactive 3D environments.',
    skills: ['Unity', 'Unreal Engine', 'C#', 'Game Design', '3D Modeling'],
    education: [
      { degree: 'BS in Game Development', institution: 'DigiPen Institute', year: 2019 },
    ],
    certifications: ['Unity Certified Developer'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [1],
  },
  {
    id: 25,
    name: 'Amanda Foster',
    role: 'Business Analyst',
    company: 'Deloitte',
    focus: 'Business analysis, requirements gathering, process improvement',
    rating: 4.6,
    assured: false,
    experience: 5,
    hourlyRate: 72,
    bio: 'Business analyst with expertise in requirements gathering and process improvement. Helps organizations optimize their business processes.',
    skills: ['Business Analysis', 'Requirements Gathering', 'Process Improvement', 'Data Analysis', 'Documentation'],
    education: [
      { degree: 'MBA', institution: 'Kellogg School of Management', year: 2019 },
    ],
    certifications: ['CBAP', 'Agile Business Analysis'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [6, 11],
  },
  {
    id: 26,
    name: 'Jordan Smith',
    role: 'Technical Writer',
    company: 'GitHub',
    focus: 'Technical documentation, API documentation, user guides',
    rating: 4.7,
    assured: false,
    experience: 4,
    hourlyRate: 58,
    bio: 'Technical writer specializing in API documentation and developer guides. Creates clear, comprehensive documentation for technical products.',
    skills: ['Technical Writing', 'API Documentation', 'Markdown', 'Git', 'Documentation Tools'],
    education: [
      { degree: 'BA in English', institution: 'University of Michigan', year: 2020 },
    ],
    certifications: ['Technical Writing Certificate'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [9],
  },
  {
    id: 27,
    name: 'Victoria Chen',
    role: 'Financial Analyst',
    company: 'Goldman Sachs',
    focus: 'Financial modeling, investment analysis, Excel',
    rating: 4.8,
    assured: true,
    experience: 6,
    hourlyRate: 88,
    bio: 'Financial analyst with expertise in financial modeling and investment analysis. Helps individuals and companies make informed financial decisions.',
    skills: ['Financial Modeling', 'Excel', 'Investment Analysis', 'Valuation', 'Financial Planning'],
    education: [
      { degree: 'MBA in Finance', institution: 'Columbia Business School', year: 2018 },
    ],
    certifications: ['CFA Level 1', 'Financial Modeling Certification'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [11],
  },
  {
    id: 28,
    name: 'Marcus Johnson',
    role: 'Database Administrator',
    company: 'Oracle',
    focus: 'Database optimization, SQL tuning, data architecture',
    rating: 4.9,
    assured: true,
    experience: 10,
    hourlyRate: 98,
    bio: 'Database administrator with expertise in database optimization and data architecture. Ensures high performance and reliability of database systems.',
    skills: ['SQL', 'Database Optimization', 'PostgreSQL', 'MySQL', 'Data Architecture'],
    education: [
      { degree: 'BS in Computer Science', institution: 'University of Maryland', year: 2014 },
    ],
    certifications: ['Oracle Certified Professional', 'PostgreSQL Administrator'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [1, 3],
  },
  {
    id: 29,
    name: 'Lily Wang',
    role: 'HR Specialist',
    company: 'LinkedIn',
    focus: 'Talent acquisition, employee relations, HR policies',
    rating: 4.6,
    assured: false,
    experience: 5,
    hourlyRate: 62,
    bio: 'HR specialist with expertise in talent acquisition and employee relations. Helps companies build strong teams and positive workplace culture.',
    skills: ['Talent Acquisition', 'Employee Relations', 'HR Policies', 'Recruitment', 'Onboarding'],
    education: [
      { degree: 'BS in Human Resources', institution: 'Cornell University', year: 2019 },
    ],
    certifications: ['SHRM Certified Professional'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [11],
  },
  {
    id: 30,
    name: 'Ethan Davis',
    role: 'Video Editor',
    company: 'YouTube',
    focus: 'Video production, editing, motion graphics',
    rating: 4.7,
    assured: false,
    experience: 4,
    hourlyRate: 55,
    bio: 'Video editor specializing in content creation and motion graphics. Creates engaging video content for digital platforms.',
    skills: ['Premiere Pro', 'After Effects', 'Video Editing', 'Motion Graphics', 'Color Grading'],
    education: [
      { degree: 'BA in Film Production', institution: 'NYU Tisch', year: 2020 },
    ],
    certifications: ['Adobe Video Specialist'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [2],
  },
  {
    id: 31,
    name: 'Zoe Anderson',
    role: 'Accountant',
    company: 'PwC',
    focus: 'Financial accounting, tax preparation, auditing',
    rating: 4.8,
    assured: true,
    experience: 7,
    hourlyRate: 75,
    bio: 'Certified public accountant with expertise in financial accounting and tax preparation. Helps individuals and businesses manage their finances.',
    skills: ['Financial Accounting', 'Tax Preparation', 'Auditing', 'QuickBooks', 'Excel'],
    education: [
      { degree: 'BS in Accounting', institution: 'University of Pennsylvania', year: 2017 },
    ],
    certifications: ['CPA', 'QuickBooks Certified'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [11],
  },
  {
    id: 32,
    name: 'Noah Brown',
    role: 'Network Engineer',
    company: 'Cisco',
    focus: 'Network design, routing, switching, security',
    rating: 4.8,
    assured: true,
    experience: 8,
    hourlyRate: 90,
    bio: 'Network engineer with expertise in designing and maintaining network infrastructure. Specialized in routing, switching, and network security.',
    skills: ['Network Design', 'Routing', 'Switching', 'Cisco', 'Network Security'],
    education: [
      { degree: 'BS in Network Engineering', institution: 'Arizona State University', year: 2016 },
    ],
    certifications: ['CCNA', 'CCNP', 'Network+'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [10],
  },
  {
    id: 33,
    name: 'Chloe Taylor',
    role: 'Interior Designer',
    company: 'Houzz',
    focus: 'Space planning, color theory, sustainable design',
    rating: 4.7,
    assured: false,
    experience: 6,
    hourlyRate: 68,
    bio: 'Interior designer specializing in residential and commercial spaces. Creates functional and beautiful environments that reflect client needs.',
    skills: ['Space Planning', 'Color Theory', '3D Rendering', 'Sustainable Design', 'AutoCAD'],
    education: [
      { degree: 'BFA in Interior Design', institution: 'Parsons School of Design', year: 2018 },
    ],
    certifications: ['NCIDQ Certified'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [2],
  },
  {
    id: 34,
    name: 'Lucas Rodriguez',
    role: 'Photographer',
    company: 'Getty Images',
    focus: 'Portrait photography, product photography, editing',
    rating: 4.8,
    assured: false,
    experience: 5,
    hourlyRate: 60,
    bio: 'Professional photographer specializing in portrait and product photography. Creates stunning visual content for brands and individuals.',
    skills: ['Photography', 'Lightroom', 'Photoshop', 'Portrait Photography', 'Product Photography'],
    education: [
      { degree: 'BFA in Photography', institution: 'Art Institute of Chicago', year: 2019 },
    ],
    certifications: ['Adobe Photography Specialist'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [2],
  },
  {
    id: 35,
    name: 'Grace Kim',
    role: 'Legal Advisor',
    company: 'LegalZoom',
    focus: 'Business law, contract review, legal research',
    rating: 4.9,
    assured: true,
    experience: 8,
    hourlyRate: 115,
    bio: 'Legal advisor specializing in business law and contract review. Helps startups and businesses navigate legal complexities.',
    skills: ['Business Law', 'Contract Review', 'Legal Research', 'Compliance', 'Intellectual Property'],
    education: [
      { degree: 'JD', institution: 'Harvard Law School', year: 2016 },
    ],
    certifications: ['Bar Admission'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [11],
  },
  {
    id: 36,
    name: 'Benjamin White',
    role: 'Fitness Coach',
    company: 'Peloton',
    focus: 'Personal training, nutrition, workout programming',
    rating: 4.8,
    assured: false,
    experience: 6,
    hourlyRate: 50,
    bio: 'Certified fitness coach with expertise in personal training and nutrition. Helps clients achieve their fitness goals through personalized programs.',
    skills: ['Personal Training', 'Nutrition', 'Workout Programming', 'Strength Training', 'Cardio'],
    education: [
      { degree: 'BS in Exercise Science', institution: 'University of Texas', year: 2018 },
    ],
    certifications: ['NASM Certified Personal Trainer', 'Nutrition Specialist'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [],
  },
  {
    id: 37,
    name: 'Maya Patel',
    role: 'Language Tutor',
    company: 'Duolingo',
    focus: 'English, Spanish, French language instruction',
    rating: 4.9,
    assured: true,
    experience: 5,
    hourlyRate: 45,
    bio: 'Language tutor specializing in English, Spanish, and French. Helps students achieve fluency through interactive and engaging lessons.',
    skills: ['Language Instruction', 'ESL', 'Spanish', 'French', 'Curriculum Development'],
    education: [
      { degree: 'MA in Linguistics', institution: 'University of Cambridge', year: 2019 },
    ],
    certifications: ['TESOL', 'CELTA'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [],
  },
  {
    id: 38,
    name: 'Henry Wilson',
    role: 'Music Producer',
    company: 'Spotify',
    focus: 'Music production, audio engineering, mixing',
    rating: 4.7,
    assured: false,
    experience: 7,
    hourlyRate: 70,
    bio: 'Music producer and audio engineer with expertise in music production and mixing. Creates professional-quality audio content.',
    skills: ['Music Production', 'Audio Engineering', 'Mixing', 'Mastering', 'Ableton Live'],
    education: [
      { degree: 'BS in Audio Engineering', institution: 'Berklee College of Music', year: 2017 },
    ],
    certifications: ['Pro Tools Certified'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [],
  },
  {
    id: 39,
    name: 'Ava Martinez',
    role: 'Life Coach',
    company: 'BetterUp',
    focus: 'Career coaching, personal development, goal setting',
    rating: 4.8,
    assured: true,
    experience: 6,
    hourlyRate: 80,
    bio: 'Certified life coach specializing in career development and personal growth. Helps individuals achieve their personal and professional goals.',
    skills: ['Career Coaching', 'Personal Development', 'Goal Setting', 'Mindfulness', 'Leadership'],
    education: [
      { degree: 'MA in Psychology', institution: 'Columbia University', year: 2018 },
    ],
    certifications: ['ICF Certified Coach', 'Life Coaching Certification'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [11, 12],
  },
  {
    id: 40,
    name: 'Jack Thompson',
    role: 'Real Estate Agent',
    company: 'Zillow',
    focus: 'Property sales, market analysis, client relations',
    rating: 4.7,
    assured: false,
    experience: 8,
    hourlyRate: 65,
    bio: 'Real estate agent with expertise in property sales and market analysis. Helps clients buy and sell properties successfully.',
    skills: ['Property Sales', 'Market Analysis', 'Client Relations', 'Negotiation', 'Marketing'],
    education: [
      { degree: 'BS in Business', institution: 'University of Miami', year: 2016 },
    ],
    certifications: ['Real Estate License', 'Real Estate Broker'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [12],
  },
  {
    id: 41,
    name: 'Sofia Garcia',
    role: 'Nutritionist',
    company: 'Noom',
    focus: 'Meal planning, dietary counseling, wellness',
    rating: 4.8,
    assured: true,
    experience: 5,
    hourlyRate: 55,
    bio: 'Registered nutritionist specializing in meal planning and dietary counseling. Helps clients achieve health goals through personalized nutrition plans.',
    skills: ['Meal Planning', 'Dietary Counseling', 'Nutrition Analysis', 'Wellness', 'Health Coaching'],
    education: [
      { degree: 'MS in Nutrition', institution: 'Tufts University', year: 2019 },
    ],
    certifications: ['Registered Dietitian', 'Nutrition Specialist'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [],
  },
  {
    id: 42,
    name: 'William Chen',
    role: 'Consultant',
    company: 'McKinsey & Company',
    focus: 'Business strategy, management consulting, problem solving',
    rating: 4.9,
    assured: true,
    experience: 9,
    hourlyRate: 150,
    bio: 'Management consultant with expertise in business strategy and problem-solving. Helps organizations improve performance and achieve strategic goals.',
    skills: ['Business Strategy', 'Management Consulting', 'Problem Solving', 'Data Analysis', 'Presentation'],
    education: [
      { degree: 'MBA', institution: 'Harvard Business School', year: 2015 },
    ],
    certifications: ['Management Consulting Certificate'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [6, 11],
  },
  {
    id: 43,
    name: 'Emily Davis',
    role: 'Event Planner',
    company: 'Eventbrite',
    focus: 'Event coordination, vendor management, logistics',
    rating: 4.7,
    assured: false,
    experience: 5,
    hourlyRate: 58,
    bio: 'Event planner specializing in corporate and social events. Coordinates seamless events from planning to execution.',
    skills: ['Event Planning', 'Vendor Management', 'Logistics', 'Budget Management', 'Coordination'],
    education: [
      { degree: 'BS in Hospitality Management', institution: 'Cornell University', year: 2019 },
    ],
    certifications: ['Certified Meeting Professional'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [11],
  },
  {
    id: 44,
    name: 'Alexander Park',
    role: 'Trading Analyst',
    company: 'Bloomberg',
    focus: 'Financial markets, trading strategies, risk management',
    rating: 4.8,
    assured: true,
    experience: 7,
    hourlyRate: 95,
    bio: 'Trading analyst with expertise in financial markets and trading strategies. Helps traders make informed investment decisions.',
    skills: ['Financial Markets', 'Trading Strategies', 'Risk Management', 'Technical Analysis', 'Bloomberg Terminal'],
    education: [
      { degree: 'MS in Finance', institution: 'NYU Stern', year: 2017 },
    ],
    certifications: ['Series 7', 'CFA Level 2'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [3],
  },
  {
    id: 45,
    name: 'Hannah Lee',
    role: 'Public Relations Specialist',
    company: 'Edelman',
    focus: 'Media relations, crisis management, brand communication',
    rating: 4.7,
    assured: false,
    experience: 5,
    hourlyRate: 68,
    bio: 'PR specialist with expertise in media relations and crisis management. Helps brands build positive public image and manage communications.',
    skills: ['Media Relations', 'Crisis Management', 'Brand Communication', 'Press Releases', 'Social Media'],
    education: [
      { degree: 'BA in Communications', institution: 'Northwestern University', year: 2019 },
    ],
    certifications: ['PRSA Accreditation'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [4],
  },
  {
    id: 46,
    name: 'Samuel Brown',
    role: 'Architect',
    company: 'Gensler',
    focus: 'Architectural design, CAD, building codes',
    rating: 4.8,
    assured: true,
    experience: 8,
    hourlyRate: 85,
    bio: 'Licensed architect specializing in commercial and residential design. Creates functional and aesthetically pleasing architectural solutions.',
    skills: ['Architectural Design', 'AutoCAD', 'Revit', 'Building Codes', '3D Modeling'],
    education: [
      { degree: 'MArch', institution: 'Harvard GSD', year: 2016 },
    ],
    certifications: ['Licensed Architect', 'LEED Certified'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [2],
  },
  {
    id: 47,
    name: 'Natalie Johnson',
    role: 'Veterinarian',
    company: 'Banfield Pet Hospital',
    focus: 'Animal care, veterinary medicine, pet health',
    rating: 4.9,
    assured: true,
    experience: 6,
    hourlyRate: 90,
    bio: 'Licensed veterinarian with expertise in animal care and veterinary medicine. Provides compassionate care for pets and helps pet owners.',
    skills: ['Veterinary Medicine', 'Animal Care', 'Surgery', 'Diagnostics', 'Pet Health'],
    education: [
      { degree: 'DVM', institution: 'Cornell University College of Veterinary Medicine', year: 2018 },
    ],
    certifications: ['Licensed Veterinarian'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [],
  },
  {
    id: 48,
    name: 'Tyler Moore',
    role: 'Mechanical Engineer',
    company: 'Tesla',
    focus: 'Product design, CAD, manufacturing processes',
    rating: 4.8,
    assured: true,
    experience: 7,
    hourlyRate: 88,
    bio: 'Mechanical engineer specializing in product design and manufacturing. Designs innovative products and optimizes manufacturing processes.',
    skills: ['Product Design', 'CAD', 'SolidWorks', 'Manufacturing', 'Prototyping'],
    education: [
      { degree: 'BS in Mechanical Engineering', institution: 'MIT', year: 2017 },
    ],
    certifications: ['SolidWorks Certified'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [1],
  },
  {
    id: 49,
    name: 'Luna Rodriguez',
    role: 'Translator',
    company: 'Google Translate',
    focus: 'Translation services, multilingual communication',
    rating: 4.7,
    assured: false,
    experience: 5,
    hourlyRate: 52,
    bio: 'Professional translator specializing in multiple languages. Provides accurate translation services for businesses and individuals.',
    skills: ['Translation', 'Multilingual Communication', 'Proofreading', 'Localization', 'Language Services'],
    education: [
      { degree: 'MA in Translation Studies', institution: 'University of Geneva', year: 2019 },
    ],
    certifications: ['ATA Certified Translator'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    courses: [9],
  },
  {
    id: 50,
    name: 'Owen Taylor',
    role: 'Investment Banker',
    company: 'JPMorgan Chase',
    focus: 'M&A, capital markets, financial modeling',
    rating: 4.9,
    assured: true,
    experience: 10,
    hourlyRate: 140,
    bio: 'Investment banker with expertise in M&A and capital markets. Helps companies raise capital and execute strategic transactions.',
    skills: ['M&A', 'Capital Markets', 'Financial Modeling', 'Valuation', 'Deal Execution'],
    education: [
      { degree: 'MBA in Finance', institution: 'Wharton School', year: 2014 },
    ],
    certifications: ['Series 79', 'CFA'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    courses: [11],
  },
]

// Dashboard/Home page: featured mentors for quick recommendation
export const homeMentorShowcase = [
  {
    name: 'James Smith',
    experience: '8 years experience',
    role: 'Mobile Application developer',
    rating: 4,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=faces',
  },
  {
    name: 'Liam Miller',
    experience: '13 years experience',
    role: 'Mobile Application developer',
    rating: 4,
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=faces',
  },
  {
    name: 'Sarah Chen',
    experience: '10 years experience',
    role: 'React Native Expert',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=faces',
  },
  {
    name: 'David Park',
    experience: '12 years experience',
    role: 'Full Stack Developer',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=faces',
  },
  {
    name: 'Emma Wilson',
    experience: '9 years experience',
    role: 'UI/UX Designer',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=faces',
  },
  {
    name: 'Michael Brown',
    experience: '15 years experience',
    role: 'DevOps Engineer',
    rating: 4,
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=faces',
  },
  {
    name: 'Sophia Martinez',
    experience: '7 years experience',
    role: 'Data Scientist',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=faces',
  },
  {
    name: 'Ryan Taylor',
    experience: '11 years experience',
    role: 'Backend Developer',
    rating: 4,
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=faces',
  },
  {
    name: 'Olivia Davis',
    experience: '6 years experience',
    role: 'Frontend Developer',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=faces',
  },
]

// Dashboard/Home page: skills marquee icons
export const homeSkillsIcons = [
  { name: 'GitHub', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg' },
  { name: 'Flutter', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg' },
  { name: 'React', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
  { name: 'TypeScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
  { name: 'Next.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg' },
  { name: 'Node.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
  { name: 'Python', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
  { name: 'Vue.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg' },
  { name: 'Angular', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg' },
  { name: 'Tailwind CSS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg' },
  { name: 'PostgreSQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
  { name: 'MongoDB', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
  { name: 'Docker', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
  { name: 'Kubernetes', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg' },
  { name: 'AWS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg' },
  { name: 'GraphQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg' },
  { name: 'Redis', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg' },
  { name: 'TensorFlow', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg' },
]

// Dashboard/Home page: market-highlight courses for hero stats
export const homeMarketCourses = [
  {
    name: 'Dart development',
    marketStanding: '3rd on market 2025',
    description:
      "High demand for Dart specialists exists in junior to senior software engineering roles due to Flutter's growth.",
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dart/dart-original.svg',
  },
  {
    name: 'React Native',
    marketStanding: '1st on market 2025',
    description:
      'Leading framework for cross-platform mobile development with growing industry adoption.',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
  },
  {
    name: 'Flutter Development',
    marketStanding: '2nd on market 2025',
    description:
      'Rapidly growing framework for building beautiful, natively compiled applications.',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg',
  },
  {
    name: 'Python Programming',
    marketStanding: '1st on market 2025',
    description:
      'Most versatile programming language used in web development, data science, AI, and automation.',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
  },
  {
    name: 'Node.js Backend',
    marketStanding: '2nd on market 2025',
    description:
      'Server-side JavaScript runtime for building scalable and efficient web applications.',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
  },
  {
    name: 'JavaScript Mastery',
    marketStanding: '1st on market 2025',
    description:
      'Essential programming language for web development, frontend, and full-stack applications.',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
  },
  {
    name: 'AWS Cloud',
    marketStanding: '1st on market 2025',
    description:
      'Leading cloud platform for deploying and managing scalable applications and infrastructure.',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
  },
  {
    name: 'Docker & Kubernetes',
    marketStanding: '2nd on market 2025',
    description:
      'Containerization and orchestration tools essential for modern DevOps and deployment workflows.',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
  },
  {
    name: 'Machine Learning',
    marketStanding: '3rd on market 2025',
    description:
      'Cutting-edge AI and ML technologies for building intelligent systems and data-driven solutions.',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg',
  },
]

// Dashboard/Home page: progress graph data (last 8 weeks)
export const homeProgressData = [
  { week: 'W1', completion: 35, engagement: 78, assignments: 55 },
  { week: 'W2', completion: 40, engagement: 68, assignments: 30 },
  { week: 'W3', completion: 42, engagement: 70, assignments: 35 },
  { week: 'W4', completion: 38, engagement: 62, assignments: 10 },
  { week: 'W5', completion: 50, engagement: 75, assignments: 75 },
  { week: 'W6', completion: 45, engagement: 12, assignments: 45 },
  { week: 'W7', completion: 70, engagement: 78, assignments: 30 },
  { week: 'W8', completion: 82, engagement: 98, assignments: 30 },
]

// Dashboard/Home page: upcoming sessions stack
export const homeUpcomingSessions = [
  {
    id: 1,
    time: '10.00',
    period: 'AM',
    location: 'classroom 208',
    course: 'mobile application',
    mentor: 'by Amelie Griffith',
  },
  {
    id: 2,
    time: '02.30',
    period: 'PM',
    location: 'classroom 105',
    course: 'React Advanced Patterns',
    mentor: 'by Sarah Chen',
  },
  {
    id: 3,
    time: '04.00',
    period: 'PM',
    location: 'classroom 312',
    course: 'UI/UX Design Principles',
    mentor: 'by Michael Torres',
  },
  {
    id: 4,
    time: '11.00',
    period: 'AM',
    location: 'classroom 201',
    course: 'Python Programming',
    mentor: 'by David Park',
  },
]

// Calendar page: scheduled sessions
export const calendarSessions = [
  {
    id: 1,
    title: 'React Advanced Patterns',
    mentor: 'Sarah Chen',
    time: '2:00 PM - 3:00 PM',
    date: 'Today',
    type: 'mentorship',
  },
  {
    id: 2,
    title: 'UI/UX Design Review',
    mentor: 'Michael Torres',
    time: '10:00 AM - 11:00 AM',
    date: 'Tomorrow',
    type: 'review',
  },
  {
    id: 3,
    title: 'Data Science Office Hours',
    mentor: 'Emily Johnson',
    time: '4:00 PM - 5:00 PM',
    date: 'Today',
    type: 'office-hours',
  },
  {
    id: 4,
    title: 'Assignment Deadline',
    time: '11:59 PM',
    date: 'Friday',
    type: 'deadline',
  },
]

// Helper function to get mentors by course
export const getMentorsByCourse = (courseId) => {
  return mentors.filter((mentor) => mentor.courses.includes(courseId))
}

// Helper function to get mentor by ID
export const getMentorById = (id) => {
  return mentors.find((mentor) => mentor.id === id)
}

// Helper function to search mentors
export const searchMentors = (query) => {
  const lowerQuery = query.toLowerCase()
  return mentors.filter(
    (mentor) =>
      mentor.name.toLowerCase().includes(lowerQuery) ||
      mentor.role.toLowerCase().includes(lowerQuery) ||
      mentor.company.toLowerCase().includes(lowerQuery) ||
      mentor.focus.toLowerCase().includes(lowerQuery) ||
      mentor.skills.some((skill) => skill.toLowerCase().includes(lowerQuery)),
  )
}

// Student Profile Data
export const studentProfileData = {
  name: 'John Doe',
  email: 'john.doe@example.com',
  role: 'Software Developer',
  bio: 'Passionate about learning and building great products. Currently focusing on React and modern web development. Always eager to learn new technologies and contribute to meaningful projects.',
  location: 'San Francisco, CA',
  joinedDate: 'January 2024',
  avatar: 'JD',
  enrolledCourses: [
    {
      id: 1,
      name: 'Full-Stack Web Development',
      category: 'Programming',
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=400&q=80',
      progress: 75,
      status: 'In Progress',
      enrolledDate: 'Jan 15, 2024',
      completionDate: null,
    },
    {
      id: 2,
      name: 'UI/UX Design Mastery',
      category: 'Design',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=400&q=80',
      progress: 100,
      status: 'Completed',
      enrolledDate: 'Dec 1, 2023',
      completionDate: 'Feb 20, 2024',
    },
    {
      id: 3,
      name: 'Data Science & Analytics',
      category: 'Data',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=400&q=80',
      progress: 45,
      status: 'In Progress',
      enrolledDate: 'Feb 10, 2024',
      completionDate: null,
    },
    {
      id: 7,
      name: 'Mobile App Development',
      category: 'Programming',
      image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=400&q=80',
      progress: 30,
      status: 'In Progress',
      enrolledDate: 'Mar 1, 2024',
      completionDate: null,
    },
  ],
  certificates: [
    {
      id: 1,
      name: 'Full-Stack Web Development Certificate',
      issuer: 'Internify',
      issueDate: 'Feb 20, 2024',
      credentialId: 'INT-FSWD-2024-001',
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=400&q=80',
    },
    {
      id: 2,
      name: 'UI/UX Design Mastery Certificate',
      issuer: 'Internify',
      issueDate: 'Feb 20, 2024',
      credentialId: 'INT-UX-2024-002',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=400&q=80',
    },
    {
      id: 3,
      name: 'React Advanced Patterns',
      issuer: 'Internify',
      issueDate: 'Jan 15, 2024',
      credentialId: 'INT-REACT-2024-003',
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=400&q=80',
    },
    {
      id: 4,
      name: 'JavaScript Fundamentals',
      issuer: 'Internify',
      issueDate: 'Dec 10, 2023',
      credentialId: 'INT-JS-2023-004',
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=400&q=80',
    },
    {
      id: 5,
      name: 'Node.js Backend Development',
      issuer: 'Internify',
      issueDate: 'Nov 25, 2023',
      credentialId: 'INT-NODE-2023-005',
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=400&q=80',
    },
  ],
  education: [
    {
      id: 1,
      degree: 'Bachelor of Science in Computer Science',
      institution: 'University of California, Berkeley',
      startYear: 2020,
      endYear: 2024,
      gpa: '3.8',
      description: 'Focused on software engineering, algorithms, and web development. Completed capstone project on full-stack web applications.',
    },
    {
      id: 2,
      degree: 'High School Diploma',
      institution: 'San Francisco High School',
      startYear: 2016,
      endYear: 2020,
      gpa: '3.9',
      description: null,
    },
  ],
  internships: [
    {
      id: 1,
      title: 'Software Engineering Intern',
      company: 'TechCorp Inc.',
      location: 'San Francisco, CA',
      startDate: 'June 2023',
      endDate: 'August 2023',
      description: 'Developed and maintained web applications using React and Node.js. Collaborated with senior engineers to implement new features and fix bugs. Participated in code reviews and agile development processes.',
      skills: ['React', 'Node.js', 'JavaScript', 'Git', 'Agile'],
    },
    {
      id: 2,
      title: 'Frontend Development Intern',
      company: 'StartupXYZ',
      location: 'Remote',
      startDate: 'September 2023',
      endDate: 'December 2023',
      description: 'Built responsive user interfaces for web applications. Worked closely with designers to implement pixel-perfect designs. Optimized application performance and user experience.',
      skills: ['React', 'TypeScript', 'CSS', 'Figma', 'Responsive Design'],
    },
  ],
  projects: [
    {
      id: 1,
      title: 'E-Commerce Platform',
      type: 'Personal Project',
      startDate: 'January 2024',
      endDate: 'March 2024',
      description: 'Full-stack e-commerce application built with React, Node.js, and MongoDB. Features include user authentication, product catalog, shopping cart, and payment integration. Deployed on AWS.',
      skills: ['React', 'Node.js', 'MongoDB', 'Express', 'AWS', 'Stripe API'],
      link: 'https://github.com/johndoe/ecommerce-platform',
    },
    {
      id: 2,
      title: 'Task Management App',
      type: 'Academic Project',
      startDate: 'September 2023',
      endDate: 'November 2023',
      description: 'Collaborative task management application with real-time updates. Built using React for frontend and Firebase for backend. Features drag-and-drop interface and team collaboration tools.',
      skills: ['React', 'Firebase', 'JavaScript', 'CSS', 'Real-time Updates'],
      link: 'https://github.com/johndoe/task-manager',
    },
    {
      id: 3,
      title: 'Weather Dashboard',
      type: 'Personal Project',
      startDate: 'May 2023',
      endDate: 'June 2023',
      description: 'Weather dashboard application that displays current weather and forecasts for multiple cities. Uses OpenWeatherMap API and features interactive charts and location-based search.',
      skills: ['React', 'JavaScript', 'API Integration', 'Chart.js', 'CSS'],
      link: 'https://github.com/johndoe/weather-dashboard',
    },
  ],
}

